apiVersion: apps/v1
kind: Deployment # what to create?
metadata:
  name: mariadb-deployment
spec: # specification for deployment resource
  replicas: 2 # how many replicas of pods we want to create
  selector:
    matchLabels:
      app: mariadb
  template: # blueprint for pods
    metadata:
      labels:
        app: mariadb # service will look for this label
    spec: # specification for pods
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306 #default one
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: anel # works, don't use strings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sequelize-deployment
spec:
  replicas: 3  # Ajuste o número de réplicas conforme necessário
  selector:
    matchLabels:
      app: sequelize
  template:
    metadata:
      labels:
        app: sequelize
    spec:
      containers:
      - name: sequelize-container
        image: luismartorano/sequelize:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sequelize-service
spec:
  selector:
    app: sequelize
  ports:
    - protocol: TCP
      port: 80  # Ajuste a porta conforme necessário
      targetPort: 80  # Ajuste a porta do container conforme necessário
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306  # Ajuste a porta conforme necessário
      targetPort: 3306  # Ajuste a porta do container conforme necessário
  type: ClusterIP
